<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\CustomizationPackage.props" />

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Dynamics.Commerce.Sdk.Pos" Version="9.51.*" />
    <PackageReference Include="Microsoft.TypeScript.MSBuild" Version="5.*" />
  </ItemGroup>

  <!-- Referencia al proyecto CRT para generar TypeScript proxy automáticamente -->
  <ItemGroup>
    <ProjectReference Include="..\CommerceRuntime\RegenerateFE.CommerceRuntime.csproj" />
  </ItemGroup>

</Project>
